server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: q123456789
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      # jpa打印sql语句
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    # Redis服务器地址
    host:
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
         # 连接池最大连接数（使用负值表示没有限制）
         max-active: 1000
         # 连接池中的最小空闲连接
         min-idle: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         #max-wait: -1
         # 连接池中的最大空闲连接
         max-idle: 10
  rabbitmq:
    host:
    port: 5672
    username: yemingrujing
    password: gw123456
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 开启ACK
        acknowledge-mode: manual
        # 消费者的最小数量
        concurrency: 5
        # 消费者的最大数量
        max-concurrency: 10
        # 在单个请求中处理的消息个数，他应该大于等于事务数量
        prefetch: 5
        # 启动时自动启动容器	true
        auto-startup: true
        # 投递失败时是否重新排队
        default-requeue-rejected: true
        retry:
          # 消费者端的重试
          enabled: true
      direct:
        # 开启ACK
        acknowledge-mode: manual
        retry:
          # 消费者端的重试
          enabled: true
  data:
    mongodb:
      host:
      username: test
      password: q123456789
      port: 27017
      database: test
      repositories:
        type: auto
elasticsearch:
  hostname1:
  port1: 9200
  username:
  password:
# jpa日志打印sql参数
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace